### ISSUE TITLE
Old version published

### ISSUE THREAD

**Issue by ChrisMacNaughton** [ceph/ceph-rust#17]
Please bump the version of ceph-rust on crates.io, the changes are getting fairly drastic at this point: https://github.com/ceph/ceph-rust/compare/a7a10ee8606dce3050626359e56ec3945a006978...master . I want ti publish my [ceph-client](https://github.com/CentauriSolutions/ceph_client) crate but can't because I use features that are not yet on crates.io

**Comment by ChrisMacNaughton** [comment]
@hanscj1 ?

**Comment by cholcombe973** [comment]
I'm working with the owner to add myself so we can push this more often.

**Comment by cholcombe973** [comment]
Migrating this over to the ceph crates on crates.io: https://crates.io/crates/ceph
