### ISSUE TITLE
Tests failing on Beta & Nightly

### ISSUE THREAD

**Issue by ChrisMacNaughton** [ceph/ceph-rust#30]
It looks like the workspace `test --all` command has expanded to include doc tests so [this line](https://github.com/ceph/ceph-rust/blob/master/src/ceph.rs#L1483) is causing beta to fail tests, it should either be correct code (with a comment of the variable nature), be replaced with `Vec::new()`, or be explicitly excluded from being built

**Comment by cholcombe973** [comment]
Thanks for spotting this.  I've put up a PR which looks to have fixed it.
