### ISSUE TITLE
Dependencies unnecessarily strict?

### ISSUE THREAD

**Issue by eastern-grey** [ceph/ceph-rust#39]
Hi there,

I was having trouble including this crate in a project that uses some other crates, because the other crates required a newer byteorder version, and cargo doesn't allow two different minor versions:

```
error: failed to select a version for `byteorder`.
    ... required by package `ceph v2.0.0`
    ... which is depended on by `testing v0.1.0 (/code/rust/testing)`
versions that meet the requirements `~1.2` are: 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0

all possible versions conflict with previously selected packages.

  previously selected package `byteorder v1.3.2`
```

For crates above 1.0.0., minor version increases should not be introducing breaking changes, so perhaps the dependency should be written as  "^1.2"  or even "1" instead of "~1.2". Making this change in a local copy has allowed me to use the crate. Nom and serde could probably be updated as well.

Thank you for making this crate available!

**Comment by cholcombe973** [comment]
Sure, happy to have someone using it!  If you'd like to put in a PR for the dependency changes i'd be happy to review it.  If not then it might take me a few days to get the changes ready.  There's a few compile errors in upgrading nom and bitflags that need fixing.

**Comment by eastern-grey** [comment]
Bitflags is <1.0 so will likely break, but it seems to build for me (with latest stable release) when all the >= 1.0 items (including nom) are changed:

```
[dependencies]
bitflags = "~0.8"
byteorder = "1"
libc = "~0.2"
log = "~0.4"
nom = "3"
serde_derive = "1"
serde = "1"
serde_json = "1"
uuid = {version = "~0.7", features = ["serde"] }
rustc-serialize = "~0.3"
```
