### ISSUE TITLE
Add support for Rados striper

### ISSUE THREAD

**Issue by bancek** [ceph/ceph-rust#45]
I've added bindings for `libradosstriper`. Is there any interest to add this to upstream project? It could be added as an optional feature.

https://github.com/bancek/ceph-rust/commit/dfee5ad48df9f6d7743401dd485bd2f5b655953f

**Comment by cholcombe973** [comment]
Yeah absolutely! PR it 😎

**Comment by bancek** [comment]
I've opened #46

**Comment by cholcombe973** [comment]
I can this can probably be a minor release.  Do you agree?

**Comment by bancek** [comment]
Yes, I think it is safe to do a minor release. Linking `libradosstriper` is only required with feature`rados_striper` so it should not break backward compatibility. I've tried to build an example without `libradosstriper` installed and it works.

Do you have any projects which you can try to build from `master` before doing the release?
