### ISSUE TITLE
Project Status Checkin

### ISSUE THREAD

**Issue by nyarly** [ceph/ceph-rust#83]
I hate to do this, but is this project still alive? There's a few PRs that seem good and haven't been accepted (or commented on), and I'm now finding that `CephClient.osd_metadata()` crashes against a Pacific install.

Could we get an honest assessment of how this project is maintained?

attn: @cholcombe973

**Comment by cholcombe973** [comment]
I honestly don't know what the status is on the project. I'm no longer an admin on this repo and I passed ownership over to RedHat. It seems like it has not had much movement after that. I was hoping they would run with it. I would try to get on contact with one of the Ceph admins to see what their plans are for it.

**Comment by cholcombe973** [comment]
Maybe @liewegas knows whom to contact?

**Comment by Xuanwo** [comment]
Yes, for now, let's go! I just received permission to work on this project, and I'm going to revive it. Welcome to the development team!
